# Generated by Django 2.2.11 on 2020-10-21 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20201021_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='remarks',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='备注'),
        ),
    ]
